### ISSUE TITLE
Let's talk PCI compliance!

### ISSUE THREAD

**Issue by ghost** [themeteorchef/saas-stripe#21]
Hi Ryan,

I made this comment: http://themeteorchef.com/recipes/building-a-saas-with-meteor-stripe-part-1/#comment-1921331622

Let's talk here. :) Where do you want to start?

**Comment by themeteorchef** [comment]
Howdy! Thank you for providing detailed info on all of this :)

Honestly I'm not sure where would be best. Top of mind is making sure that the information in the recipe is factually accurate and won't lead any developers down a wayward path. 

What in the code would need to be refactored in order to get around all of this PCI hullabaloo? If I understand both of your comments correctly, an extra step for token generation would need to be done using stripe.js on the _client_ first and then passing _that_ result to the server to create a customer?

**Comment by themeteorchef** [comment]
P.S. What is the best way to know whether or not you're remaining compliant? I'd seen Stripe's original help doc on PCI compliance, but the one you linked about DSS 3.0 is news to me. 

This is one of those "glad to comply, but how the hell do I comply" type of questions :p

**Comment by CaptSaltyJack** [comment]
Don't sweat it, I went through the same thing and spent *days* on this, learning as much as I could. A total pain, but no one wants to get a call from American Express with a PCI violation if someone should report fraud and your website is on their statement!

If you follow the information below, you should be compliant. A sure-fire way of testing your SaaS (or someone else's) is to open up your browser's dev tools and go to the Network tab, load up a checkout page, and submit a credit card number. If you see it being sent to the server, untokenized, that's bad news. Unless of course, said SaaS is completely compliant under SAQ A-EP.

I'm a bit short on time today, but here's a good starting point. I did a PR to fix the README file for the `mrgalaxy:stripe` package. It has example code on how I handle Stripe transactions compliantly.

https://github.com/tyler-johnson/stripe-meteor

The Stripe documentation ([JS side](https://stripe.com/docs/stripe.js)) covers how to handle things on the client end. [This tutorial](https://stripe.com/docs/tutorials/forms) was also really helpful to me.

The full API reference shows how to [create a charge](https://stripe.com/docs/api#create_charge) using the new `source` parameter which contains the stripe token created on the client side.

I don't know the details at the moment, but I know you can also create a customer by creating a token, so they can supply a credit card and then you simply use Stripe's API to make a new customer with their default card. That was also in the API reference as well.

If I were in your shoes, here's how I'd modify your tutorial:
* Use the `mrgalaxy:stripe` package, but that's just me because I'm not a fan of mixing npm with meteor. ;)
* Using the `name` attribute for things like `<input name="ccNum" id="cc-num">` makes me nervous. Sure, you're using `e.preventDefault()` to stop the form from actually posting, but if there's a Javascript error looming around and something breaks, the `preventDefault` call will be ignored, and the user's CC data will be posted to your server. If this were my project, I'd find a different validation package/plugin that would let me reference inputs by ID instead, or just write my own. Stripe.js also has some built-in validation calls, I just noticed.

Let me know what you think of all that. Hope it helps!

**Comment by CaptSaltyJack** [comment]
Also, note the Stripe API upgrade note (about the new `source` attribute).

![api_key_settings](https://cloud.githubusercontent.com/assets/440132/6770333/30192150-d07a-11e4-979d-89675bab213e.png)

I also logged into Stripe to try to find where you can download a pre-filled SAQ A questionnaire in case you run into PCI violation issues. It's cool that they provide that for you. I could've *sworn* it was under settings somewhere, but I can't find it now.

**Comment by CaptSaltyJack** [comment]
Hey Ryan, just wanted to check in! Was this stuff helpful? Do you plan to eventually modify the tutorial?

**Comment by themeteorchef** [comment]
Hey Jack, yes very helpful. 

I do plan to modify the tutorial per your notes but I'm not sure when I'll get around to it (have to consider the writing portion along with the code, too, and determine time to complete).

**Comment by voidale** [comment]
+1

**Comment by themeteorchef** [comment]
Ack! This is on my radar, I promise. Thanks for showing your interest :)

**Comment by bcohn12** [comment]
Fantastic tutorial! I'd love to use this but really need PCI compliance. What's the status on this?

**Comment by themeteorchef** [comment]
@bcohn12 fixed! You were the finally shove: http://themeteorchef.com/recipes/building-a-saas-with-meteor-stripe-part-1/. Both parts 1 and 2 are updated and should be PCI compliant now (moved card data handling to the client). Note: I've swapped out the NPM package for the `mrgalaxy:stripe` Meteor package. This requires a handful of refactors to make sure you're calling the correct APIs. 

If you have any questions, let me know!

**Comment by bcohn12** [comment]
fantastic! thanks so much, I'm looking through your commits now to learn how you did it.
